# Generated by Django 3.1.3 on 2020-11-25 06:41

import app.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(default=app.models.company.generate_company_id, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_per_unit', models.FloatField()),
                ('time_to_produce', models.IntegerField()),
                ('require_factory', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_to_produce', models.CharField(max_length=255)),
                ('product_from_material', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
