# Generated by Django 3.1.3 on 2020-12-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201202_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('building_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('building_rent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('upgrade_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('upgrade_cost_growth', models.DecimalField(decimal_places=4, max_digits=20)),
                ('max_employees', models.BigIntegerField()),
                ('max_employees_growth', models.DecimalField(decimal_places=4, max_digits=20)),
                ('max_storage', models.BigIntegerField()),
                ('max_storage_growth', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
