# Generated by Django 3.1.3 on 2020-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_companycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='can_sell',
            field=models.BooleanField(default=False),
        ),
    ]
