# Generated by Django 3.1.3 on 2020-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_companycategory_can_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
