# Generated by Django 3.1.3 on 2020-12-05 04:46

from app.models.company.land_own import *
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20201203_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('max_land_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('min_land_cost', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='LandOwn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(default=generate_unique_id, max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='', max_length=255)),
                ('buy_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_type', models.CharField(max_length=255)),
                ('corporation_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(editable=False)),
                ('level', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('max_storage', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('employees', models.IntegerField(default=0)),
                ('max_employees', models.IntegerField(default=0)),
                ('current_rent_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
