# Generated by Django 3.1.3 on 2020-12-05 06:32

from app.models.company.corporation import generate_unique_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_corporation_land_landown'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='corporation_id',
            field=models.CharField(default=generate_unique_id, max_length=255),
        ),
    ]
