# Generated by Django 3.1.3 on 2020-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_corporation_corporation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landown',
            name='rent_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
