# Generated by Django 3.1.3 on 2020-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_landown_rent_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='continent',
            field=models.CharField(default='asia', max_length=255),
        ),
    ]
