# Generated by Django 3.1.3 on 2020-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201125_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('can_sell', models.BooleanField(default=False)),
                ('storage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='qualification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
